server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      start-saga: start-saga
      orchestrator: orchestrator
      finish-sucess: finish-sucess
      finish-fail: finish-fail
    consumer:
      group-id: orchestrator-group
      auto-offset-reset: latest
logging:
  level:
    org:
      apache:
        kafka: OFF