server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/payment-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    template:
      default-topic: teste
    consumer:
      group-id: payment-group
      auto-offset-reset: latest
logging:
  level:
    org:
      apache:
        kafka: OFF